/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const ucsRoomMgmtApiVer = require("./docs/openapi/ucs/versions.json");
const {
    versionSelector,
    versionCrumb,
} = require("docusaurus-plugin-openapi-docs/lib/sidebars/utils");

const sidebars = {
    overview: [
        {
            type: "autogenerated",
            dirName: "10_overview",
        },
    ],
    development: [
        {
            type: "autogenerated",
            dirName: "20_development",
        },
    ],
    deployment: [
        {
            type: "autogenerated",
            dirName: "30_deployment",
        },
    ],
    web: [
        {
            type: "autogenerated",
            dirName: "40_web",
        },
    ],
    iam: [
        {
            type: "autogenerated",
            dirName: "50_iam",
        },
    ],
    ucs: [
        {
            type: "autogenerated",
            dirName: "60_ucs",
        },
    ],
    "ucsAPI-v2": [
        {
            type: "html",
            defaultStyle: true,
            value: versionSelector(ucsRoomMgmtApiVer),
            className: "version-button",
        },
        {
            type: "html",
            defaultStyle: true,
            value: versionCrumb(`v2`),
        },
        {
            type: "category",
            label: "Room Management",
            link: {
                type: "generated-index",
                title: "UCS Room Mangement API (v2)",
                slug: "/ucs/api",
            },
            items: require("./docs/openapi/ucs/sidebar"),
        },
    ],
    "ucsAPI-v1": [
        {
            type: "html",
            defaultStyle: true,
            value: versionSelector(ucsRoomMgmtApiVer),
            className: "version-button",
        },
        {
            type: "html",
            defaultStyle: true,
            value: versionCrumb(`v1`),
        },
        {
            type: "category",
            label: "Room Management",
            link: {
                type: "generated-index",
                title: "UCS Room Mangement API (v1)",
                slug: "/ucs/api/v1",
            },
            items: require("./docs/openapi/ucs/v1/sidebar"),
        },
    ],
    gis: [
        {
            type: "autogenerated",
            dirName: "70_gis",
        },
    ],
    rnr: [
        {
            type: "autogenerated",
            dirName: "80_rnr",
        },
    ],
    wfe: [
        {
            type: "autogenerated",
            dirName: "90_wfe",
        },
    ],
    documentation: [
        {
            type: "autogenerated",
            dirName: "99_documentation",
        },
    ],
};

module.exports = sidebars;
